### ISSUE TITLE
BUG: Cant use Browser back function

### ISSUE THREAD

**Issue by breadlesscode** [neos/redirecthandler-ui#41] opened 2019-11-22 09:08 UTC
## Behaviour

If you press the browsers back button on the import or export page you got the unrendered markup.

## Expected

See the backend module.

## Reproduce

1. Visit redirect handler backend module
2. Click on export redirects
3. Press the back button in your browser

**Comment by Sebobo** [comment] 2019-11-24 12:25
Can't reproduce with Brave or Safari and also I'm not sure why this should happen.
The export and import pages are normal controller actions and nothing JSy.

**Comment by breadlesscode** [comment] 2019-11-25 09:07
```
neos/redirecthandler                            4.0.2             
neos/redirecthandler-databasestorage            4.0.1
neos/redirecthandler-neosadapter                4.0.3
neos/redirecthandler-ui                         2.1.0
```

Chrome: 78.0.3904.97  - ❎ Fails
Firefox: 70.0.1 - ❎ Fails
MS Edge Beta: 79.0.309.30   - ❎ Fails (big surprise)
Safari: 13.0.3 - ✅ Works 


Sorry I also have no good Idea why this happens. If you are open DevTools and have `Disable Cache` on, you cant reproduce this error! Its the internal Browser cache that produces this error. It thinks the last response was a `application/json`-Response, but its a small HTML-Partial.

**Comment by Sebobo** [comment] 2019-11-25 09:16
Ok thx! I'll test again.

**Comment by Sebobo** [comment] 2019-11-29 11:41
I was once able to reproduce and now I can't again with any browser...

**Comment by Sebobo** [comment] 2019-12-28 07:05
Fix in https://github.com/neos/neos-development-collection/pull/2841

**Comment by Sebobo** [comment] 2020-01-21 08:53
Fix was just merged into Neos and will be in the next patch release. Therefore I'll close this.

**Closed by Sebobo** 2020-01-21 08:53 UTC
Labels: bug

**Comment by breadlesscode** [comment] 2020-01-21 09:16
Thank you for taking care of it :)
