### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'I18n' of undefined

### ISSUE THREAD

**Issue by benediktgrether** [neos/redirecthandler-ui#79] opened 2021-09-07 07:53 UTC
Hi,

we run with one of our Portals in this Issue.
```
Uncaught (in promise) TypeError: Cannot read property 'I18n' of undefined
    at main.bundle.js:formatted:20354
    at main.bundle.js:formatted:20312
    at Object.next (main.bundle.js:formatted:20325)
    at main.bundle.js:formatted:20231
    at new Promise (<anonymous>)
    at e (main.bundle.js:formatted:20208)
    at window.onload (main.bundle.js:formatted:20349)
    at t.<computed> (rocket-loader.min.js:1)
    at l (rocket-loader.min.js:1)
    at t.simulateStateAfterDeferScriptsActivation (rocket-loader.min.js:1)
``` 

But when i check the property `window.Typo3Neos.I18n` in the console and we get this callback
```
window.Typo3Neos.I18n
  u {initialized: true, __ember1631000395963: undefined, _super: undefined, __ember1631000395963_meta: p}
    initialized: true
    __ember1631000395963: undefined
    __ember1631000395963_meta: p {descs: {…}, watching: {…}, cache: {…}, source: u, proto: u}
    _super: undefined
    [[Prototype]]: u
```

I don't know if the `return setTimeout(e, 50)` time is to short? 

Our Packages that we use.
```
PACKAGES:
 Neos.Cache                                5.3.28
 Neos.ContentRepository                    4.3.19
 Neos.Diff                                 4.3.19
 Neos.Eel                                  5.3.28
 Neos.Flow                                 5.3.28
 Neos.Flow.Log                             5.3.28
 Neos.FluidAdaptor                         5.3.28
 Neos.Form                                 4.3.3
 Neos.Form.Builder                         1.3.0
 Neos.Fusion                               4.3.19
 Neos.Fusion.Afx                           1.4.1
 Neos.Imagine                              3.2.0
 Neos.Media                                4.3.19
 Neos.Media.Browser                        4.3.19
 Neos.Neos                                 4.3.19
 Neos.Neos.Ui                              4.0.14
 Neos.Neos.Ui.Compiled                     4.0.14
 Neos.NodeTypes                            4.3.19
 Neos.NodeTypes.AssetList                  4.3.19
 Neos.NodeTypes.BaseMixins                 4.3.19
 Neos.NodeTypes.ColumnLayouts              4.3.19
 Neos.NodeTypes.ContentReferences          4.3.19
 Neos.NodeTypes.Form                       4.3.19
 Neos.NodeTypes.Html                       4.3.19
 Neos.NodeTypes.Navigation                 4.3.19
 Neos.Party                                5.0.2
 Neos.RedirectHandler                      3.0.3
 Neos.RedirectHandler.DatabaseStorage      4.1.0
 Neos.RedirectHandler.NeosAdapter          4.3.0
 Neos.RedirectHandler.Ui                   2.4.4
 Neos.Seo                                  3.0.6
 Neos.Setup                                4.0.6
 Neos.SwiftMailer                          6.0.5
 Neos.Twitter.Bootstrap                    3.0.6
 Neos.Utility.Arrays                       5.3.28
 Neos.Utility.Files                        5.3.28
 Neos.Utility.MediaTypes                   5.3.28
 Neos.Utility.ObjectHandling               5.3.28
 Neos.Utility.OpcodeCache                  5.3.28
 Neos.Utility.Pdo                          5.3.28
 Neos.Utility.Schema                       5.3.28
```

**Comment by Sebobo** [comment] 2021-09-07 08:15
Very strange, we fixed that in 2.4.2 and the check shouldn't happen if Typo3Neos is not there yet 😕

**Comment by benediktgrether** [comment] 2021-09-07 08:38
I know that you fixed it with 2.4.2 😕  i saw the old issues. 

Did you think we missed some packages ? 
On my local machine and on our dev-server we don't have this issue.

**Comment by lorenzulrich** [comment] 2021-09-08 09:42
I can confirm this issue using 2.4.2.

In Edge Chromium, the table never appears:

![image](https://user-images.githubusercontent.com/1816023/132486125-5cb7626d-e72f-4843-bf1d-280543d5dca3.png)

In Firefox 91, the table sometimes appear, sometimes not. When it doesn't, the error is slightly different:

![image](https://user-images.githubusercontent.com/1816023/132486377-954fe863-eb6d-47db-b8cc-35aad057b8b8.png)

**Comment by Sebobo** [comment] 2021-09-15 11:58
Tried reproducing with Edge and Firefox in Dev and Prod but without success 🤔

**Comment by Sebobo** [comment] 2021-09-15 11:58
Is it possible an older JS version was still cached?

**Comment by lorenzulrich** [comment] 2021-09-16 07:01
In the case mentioned, we are using Neos 4.3 LTS. Maybe that could be the reason?

**Comment by benediktgrether** [comment] 2021-09-30 08:21
@Sebobo at our case the problem is solved. We think it was a kind of caching issue with CDN.

**Comment by lorenzulrich** [comment] 2021-09-30 20:34
@Sebobo As you suspected, the problem was the outdated version 2.4.2. Updating to 2.4.4 solves the problem.

**Comment by Sebobo** [comment] 2021-10-01 06:55
Hurray, then I will close the issue :)

**Closed by Sebobo** 2021-10-01 06:55 UTC
